- name: Configure App Service with Docker image
  azure.azcollection.azure_rm_webapp:
    resource_group: "{{ resource_group }}"
    name: "{{ webapp_name }}"
    app_settings:
      DOCKER_REGISTRY_SERVER_URL: "https://{{ acr_login_server }}"
      DOCKER_REGISTRY_SERVER_USERNAME: "{{ acr_username }}"
      DOCKER_REGISTRY_SERVER_PASSWORD: "{{ acr_password }}"
      WEBSITES_PORT: "{{ backend_port }}"
      DB_HOST: "{{ db_host }}"
      DB_NAME: "{{ db_name }}"
      DB_USER: "{{ db_user }}"
      DB_PASSWORD: "{{ db_password }}"
