name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Flutter version from pubspec.yaml
        id: flutter_version
        run: |
          VERSION=$(grep flutter pubspec.yaml | awk '{print $2}' | sed 's/"//g')
          if [ -z "$VERSION" ]; then
            VERSION="stable"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.flutter_version.outputs.version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test
